#!/bin/bash
#SBATCH --job-name=CE_nestpoly
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=32
#SBATCH --ntasks-per-core=1
#SBATCH --mem-per-cpu=2900
#SBATCH --time=1-00:00:00
#SBATCH --partition=dark

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=rosa@ucsc.edu

module purge
module load intel/15.0.1  
module load intelmpi/5.0.2.044

EXE="/groups/dark/rosa/FLASH4.3/object_CE_nestpoly/flash4"
INPUT="/storage/dark/rosa/FLASH4.3/CE_nestpoly/flash.par"

srun $EXE -par_file $INPUT -i --preserve-env
